### ISSUE TITLE
Airzone API "Method not provided or not supported"

### ISSUE THREAD

**Issue by jetblack-nz** [Noltari/aioairzone#2]
Hi there,

I've seen a couple of similar issues logged for home assistant, and you helped them out together with the Airzone developer. Thanks for the great integration btw! So here it goes:

The Home Assistant and Airzone integration worked fine until my Airzone firmware was upgraded late last year to resolve an issue with one of my zones. Not sure what the firmware was before, but since the webserver 3.3.6 is running the local API is reporting an error. 

Please let me know if you need anything else, I have enabled debug logging for the integration but since the Airzone API is not responding well, not sure it's useful.

Symptoms:
- After a restart of the Airzone system (or simply using the 'Detect systems' in the Airzone app Airtools) the integration works fine through Home Assistant for a bit.
- Then after a few hours it reports the following in the log:
`Logger: homeassistant.config_entries
Source: config_entries.py:1244
First occurred: 10:12:21 AM (1 occurrences)
Last logged: 10:12:21 AM
Config entry 'Airzone 10.1.1.236:3000' for airzone integration not ready yet: error: Method not provided or not supported; Retrying in background`

I have called the Airzone API manually, see here:
`curl -s --location --request POST "http://10.1.1.236:3000/api/v1/hvac" -d '{"systemID": 127}' | jq`
`{
  "errors": [
    {
      "error": "Method not provided or not supported"
    }
  ]
}`

Versions:
Home Assistant (Docker) 2023.3.6
Frontent 20230309.1 

Airzone: 
Airzone INT
Firmware: 7.2.2
Gateway: Daikin
Firmware 2.1.1
Webserver Firmware: 3.3.6

**Comment by jetblack-nz** [comment]
Hi @dev-airzone I've seen your comments on related issues e.g. https://github.com/home-assistant/core/issues/82137 and thought you might be interested in this. Thank you

**Comment by Noltari** [comment]
Hi @jetblack-nz,

If it's working for some time and then it stops working then I bet that your device needs to be updated to a more recent firmware, so you need to contact Airzone and request them to update your device by providing the MAC address of your device.

**Comment by jetblack-nz** [comment]
Thank you @Noltari, I have contacted Airzone via email to get this looked at. If you don't mind I keep the issue open and comment any updates from the manufacturer.

**Comment by Noltari** [comment]
> Thank you @Noltari, I have contacted Airzone via email to get this looked at. If you don't mind I keep the issue open and comment any updates from the manufacturer.

Sure, I'll be happy to help if there are any changes required in order to get your device working :)

**Comment by Noltari** [comment]
@jetblack-nz I'm closing this since it's been over a month and I didn't get any updates from you.
So I'm assuming that everything is working as expected now.

**Comment by jetblack-nz** [comment]
@Noltari sorry for not replying. Airzone provided a short non-answer: "You have the last firmware version available for your hardware. It is not possible to go higher than 3.36 on AZVAFWSCLOUDC" and "The problem with the API integrations is that they use more and more memory on logs and more frequent pooling because the new hardware can handle it, but with previous hardware with less memory on the PCB, the frequent pool block the API service when the physical memory is full."

I will dig further into this, as the older firmware worked fine.

Is there a chance to configure the polling interval for your custom component? I don't need real-time data, just the temperature sensors would be great to update every hour or so...

**Comment by Noltari** [comment]
> @Noltari sorry for not replying. Airzone provided a short non-answer: "You have the last firmware version available for your hardware. It is not possible to go higher than 3.36 on AZVAFWSCLOUDC" and "The problem with the API integrations is that they use more and more memory on logs and more frequent pooling because the new hardware can handle it, but with previous hardware with less memory on the PCB, the frequent pool block the API service when the physical memory is full."

This sounds to me like something is leaking memory or not optimized at all, since it works fine for some hours and then it doesn't...

> I will dig further into this, as the older firmware worked fine.

Exactly, it makes no sense that the older firmware worked and the new doesn'...

> Is there a chance to configure the polling interval for your custom component? I don't need real-time data, just the temperature sensors would be great to update every hour or so...

I've checked and there's nothing in the API documentation stating the minimum delay between polls...
And based on my experience and the information that you provided is likely that even incrementing the scan interval will trigger the same behaviour...
I will try to contact Airzone about this to get feedback from them about a proper scan interval for older devices, how to identify them and maybe even try to make the scan interval configurable from Home Assistant...

**Comment by Noltari** [comment]
@jetblack-nz please, extract this to your custom_components folder and restart Home Assistant.
It's the same integration source code but with a scan interval of 10 minutes and 30 minutes instead of 60 seconds.
[airzone-2023.6.1-10m.zip](https://github.com/Noltari/aioairzone/files/11742543/airzone-2023.6.1-10m.zip)
[airzone-2023.6.1-30m.zip](https://github.com/Noltari/aioairzone/files/11742553/airzone-2023.6.1-30m.zip)

**Comment by jetblack-nz** [comment]
@Noltari thanks for that, I will install it on the weekend and test it out.

**Comment by Noltari** [comment]
> @Noltari thanks for that, I will install it on the weekend and test it out. 
> 

@jetblack-nz I reported this issue to Airzone and they are investigating it.
Did the higher scan interval help?

**Comment by jetblack-nz** [comment]
@Noltari it looks like the Airzone system holds on for a bit longer with the updated scan intervals, but it eventually fails. Usually after 6-12 hours.

Just making sure I have your component updated correctly, is there something specific in the logs that show that? After the HA restart it only includes below. Thank you

`[homeassistant.loader] We found a custom integration airzone which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant'`

**Comment by Noltari** [comment]
> @Noltari it looks like the Airzone system holds on for a bit longer with the updated scan intervals, but it eventually fails. Usually after 6-12 hours.

But, 6-12h is still a pretty short interval... Taking into account that we bumped the scan interval from 1 min to 1 hour, it should take a lot more time than that to fail if it was due to API requests consuming too much resources...

How long does it take to fail with the standard scan interval?

> Just making sure I have your component updated correctly, is there something specific in the logs that show that? After the HA restart it only includes below. Thank you
>
> `[homeassistant.loader] We found a custom integration airzone which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant'`

Yes, that indicates that you installed a custom component, so you're using the modified version.

**Comment by jetblack-nz** [comment]
> How long does it take to fail with the standard scan interval?
It took about 3 hours for the API to stop responding with the standard scan interval. 

I haven't had a lot of time to look into this, but I made sure that your customer code with the 30 min scan interval is installed. The Airzone system is not resetting when I do a refresh via the app, or a change of network settings on the wall controller itself. When I get a chance I'll cut the power to the whole aircon completely, that should do the trick.

**Comment by Noltari** [comment]
@jetblack-nz you may want to take a look at https://github.com/Noltari/aioairzone/issues/8 and 
Maybe your device is also suffering the segmented HTTP body and header issue...

**Comment by jetblack-nz** [comment]
Much appreciated @Noltari to notify me. I will try the updated version and see if it helps.

**Comment by Noltari** [comment]
> Much appreciated @Noltari to notify me. I will try the updated version and see if it helps.

@jetblack-nz the fix is now present on the latest version of Home Assistant.
Did it fix your issue too?

**Comment by jetblack-nz** [comment]
@Noltari thanks for letting me know. I did try this and selected the new quirks option, but Airzone returns a different error: "Invalid HTTP Content-Type: text/html".

**Comment by Noltari** [comment]
> @Noltari thanks for letting me know. I did try this and selected the new quirks option, but Airzone returns a different error: "Invalid HTTP Content-Type: text/html". 

Yes, this was solved after that.
It should be solved on the latest Home Assistant release.

**Comment by jetblack-nz** [comment]
Got it. After the error still showed up in my updated Home Assistant this morning, I removed the component using the UI, then manually cleared the Airzone custom_component folder, then gave HA a restart.

I also restarted the Airzone system.

I then added the Airzone integration, and it showed all my zones, temperatures, controls, etc. This is great, seems to be going well so far! I will monitor it and let you know how it goes.

Much appreciated.

**Comment by Noltari** [comment]
> I then added the Airzone integration, and it showed all my zones, temperatures, controls, etc. This is great, seems to be going well so far! I will monitor it and let you know how it goes.

That's great news. I'll wait for some days before closing this issue.
Anyhow, if the problem reappears just reopen it :)

**Comment by jetblack-nz** [comment]
Hi there, I'm back to the old 'Method not supported' error again. The restart of the Airzone system must have reset it and it worked fine in the beginning, until the usual issue kicked in a few hours later. 

I'm not very hopeful this will ever get resolved, until a hardware upgrade maybe? The main controller was replaced a few weeks ago on warranty (already faulty), but they kept the old web server module.

**Comment by jetblack-nz** [comment]
Thanks for your support and efforts. I will close this now. Cheers
